export const transactions = [
  {
    id: "1",
    type: "income",
    amount: 2500,
    date: "2024-01-15",
    description: "Beispielbeschreibung",
    category: "Salary",
  },
  {
    id: "2",
    type: "expense",
    amount: 50,
    date: "2024-01-16",
    description: "Yoga Session",
    category: "Hobby",
  },
  {
    id: "3",
    type: "income",
    amount: 1000,
    date: "2024-01-17",
    description: "Freelance work",
    category: "Income",
  },
  {
    id: "4",
    type: "expense",
    amount: 200,
    date: "2024-01-18",
    description: "Groceries",
    category: "Food",
  },
  {
    id: "5",
    type: "expense",
    amount: 150,
    date: "2024-01-19",
    description: "Gas",
    category: "Transportation",
  },
  {
    id: "6",
    type: "income",
    amount: 500,
    date: "2024-01-20",
    description: "Birthday gift",
    category: "Income",
  },
  {
    id: "7",
    type: "expense",
    amount: 100,
    date: "2024-01-21",
    description: "Coffee",
    category: "Food",
  },
  {
    id: "8",
    type: "expense",
    amount: 250,
    date: "2024-01-22",
    description: "Rent",
    category: "Housing",
  },
  {
    id: "9",
    type: "income",
    amount: 1000,
    date: "2024-01-23",
    description: "Bonus",
    category: "Income",
  },
  {
    id: "10",
    type: "expense",
    amount: 50,
    date: "2024-01-24",
    description: "Gym membership",
    category: "Health",
  },
];
