export const initialTransactions = [
  {
    id: "1",
    type: "Income",
    amount: 2500,
    date: "2024-01-15",
    description: "Gehalt Januar",
    category: "Salary",
  },
  {
    id: "2",
    type: "Expense",
    amount: 50,
    date: "2024-01-16",
    description: "",
    category: "Hobby",
  },
  {
    id: "3",
    type: "Income",
    amount: 1000,
    date: "2024-01-17",
    description: "Freelance work",
    category: "Salary",
  },
  {
    id: "4",
    type: "Expense",
    amount: 200,
    date: "2024-01-18",
    description: "Groceries",
    category: "Food",
  },
  {
    id: "5",
    type: "Expense",
    amount: 150,
    date: "2024-01-19",
    description: "",
    category: "Household",
  },
  {
    id: "6",
    type: "Income",
    amount: 500,
    date: "2024-01-20",
    description: "Birthday gift",
    category: "Other",
  },
  {
    id: "7",
    type: "Expense",
    amount: 50,
    date: "2024-01-24",
    description: "Gym membership",
    category: "Health",
  },
  {
    id: "8",
    type: "Expense",
    amount: 50,
    date: "2024-01-24",
    description: "this is a saving transaction",
    category: "Saving",
  },
];
export const initialGoals = [
  {
    id: "1",
    goalName: "New Zealand Trip",
    savedAmount: 2000,
    goalAmount: 15000,
  },
  {
    id: "2",
    goalName: "Car",
    savedAmount: 8000,
    goalAmount: 25000,
  },
  {
    id: "3",
    goalName: "Dream House",
    savedAmount: 25000,
    goalAmount: 500000,
  },
];
